name: easy_icon_pack
description: "Easy Icon Pack for Flutter"
version: 1.0.0
homepage: https://github.com/scadasystems/easy_icon_pack

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  lucide_icons_flutter: ^3.0.6
  hugeicons: ^0.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:


